const users = [
  {
    id: 0,
    fio: 'Иванов Иван',
    email: 'ivanov@mail.ru',
    password: 'ivanov',
    cellphone: '+79132567896',
    role: 'user',
    city: 'Barnaul',
    country: 'Russia',
  },

  {
    id: 0,
    fio: 'Петров Пётр',
    email: 'petrov@mail.ru',
    password: 'petrov',
    cellphone: '+79132338956',
    role: 'user',
    city: 'Rubtsovsk',
    country: 'Russia',
  },
  {
    id: 0,
    fio: 'Сидоров Сидор',
    email: 'sidorov@mail.ru',
    password: 'sidorov',
    cellphone: '+79132151365',
    role: 'user',
    city: 'Novosibirsk',
    country: 'Luxemburg',
  },
  {
    id: 0,
    fio: 'Винокуров Алексей',
    email: 'vinokurov@mail.ru',
    password: 'vinokurov',
    cellphone: '+79631245698',
    role: 'user',
    city: 'Novosibirsk',
    country: 'Russia',
  },
  {
    id: 0,
    fio: 'admin',
    email: 'admin',
    password: 'admin',
    cellphone: '+79324567821',
    role: 'admin',
    city: 'Moscow',
    country: 'Russia',
  },
  {
    id: 0,
    fio: 'Старченко Сергей',
    email: 'starchenko@mail.ru',
    password: 'starchenko',
    cellphone: '+7945689875',
    role: 'user',
    city: 'Barnaul',
    country: 'Russia',
  },
];

export default users;
