import type { Prognose } from '../interfaces/interfaces';

function isAutogeneratedFlag(v: unknown): boolean {
  return v === true || v === 1 || v === 'true';
}

export function normalizeScoreKey(a: number, b: number): string {
  return `${Math.min(a, b)}-${Math.max(a, b)}`;
}

export function formatNormalizedScore(key: string): string {
  const [lo, hi] = key.split('-').map(Number);
  return `${hi} - ${lo}`;
}

export type PointCounts = Record<2 | 3 | 4 | 5, number>;

export function countPrognosePoints(prognoses: Prognose[]): PointCounts {
  const counts: PointCounts = { 2: 0, 3: 0, 4: 0, 5: 0 };
  for (const p of prognoses) {
    if (p.exists !== true) continue;
    if (isAutogeneratedFlag(p.autogenerated)) continue;
    const r = p.result;
    if (r === 2 || r === 3 || r === 4 || r === 5) {
      counts[r]++;
    }
  }
  return counts;
}

export type FrequentScore = { key: string; label: string; count: number };

export function topFrequentPrognoseScores(
  prognoses: Prognose[],
  limit = 2
): FrequentScore[] {
  const map = new Map<string, number>();
  for (const p of prognoses) {
    if (p.exists !== true) continue;
    const t1 = p.team1_result;
    const t2 = p.team2_result;
    if (
      typeof t1 !== 'number' ||
      typeof t2 !== 'number' ||
      !Number.isFinite(t1) ||
      !Number.isFinite(t2)
    ) {
      continue;
    }
    const key = normalizeScoreKey(t1, t2);
    map.set(key, (map.get(key) ?? 0) + 1);
  }
  return Array.from(map.entries())
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .slice(0, limit)
    .map(([key, count]) => ({ key, label: formatNormalizedScore(key), count }));
}
