import type { Prognose } from '../interfaces/interfaces';

/** true из JSON / Prisma / строки */
function isAutogeneratedFlag(v: unknown): boolean {
  return v === true || v === 1 || v === 'true';
}

/** Класс заливки кружка с очками (таблица: `.score.*`, прогнозы: `.prognose__player-score.*`). */
export function getPrognoseScoreCircleClass(
  prognose: Pick<Prognose, 'result' | 'autogenerated'>
): string {
  const r = prognose.result;
  if (typeof r !== 'number' || !Number.isFinite(r) || r === 0) {
    return 'score_black';
  }

  if (isAutogeneratedFlag(prognose.autogenerated)) return 'score_brown';

  if (r === 2) return 'score_blue';
  if (r === 3) return 'score_green';
  if (r === 4) return 'score_aqua';
  if (r === 5) return 'score_orange';
  return 'score_black';
}
