import type { Prognose } from '../interfaces/interfaces';

/** true из JSON / Prisma / строки */
function isAutogeneratedFlag(v: unknown): boolean {
  return v === true || v === 1 || v === 'true';
}

/** Класс заливки кружка с очками (таблица: `.score.*`, прогнозы: `.prognose__player-score.*`). */
export function getPrognoseScoreCircleClass(
  prognose: Pick<Prognose, 'result' | 'autogenerated'>
): string {
  if (isAutogeneratedFlag(prognose.autogenerated)) return 'score_brown';

  let color = 'score_black';
  const r = prognose.result;
  if (r === 2) color = 'score_blue';
  if (r === 3) color = 'score_green';
  if (r === 4) color = 'score_aqua';
  if (r === 5) color = 'score_orange';
  return color;
}
